# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimpleEditor(object):
    def setupUi(self, SimpleEditor):
        SimpleEditor.setObjectName("SimpleEditor")
        SimpleEditor.resize(740, 569)
        SimpleEditor.setMinimumSize(QtCore.QSize(740, 569))
        self.centralwidget = QtWidgets.QWidget(SimpleEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.areaCodigo = QtWidgets.QTextEdit(self.centralwidget)
        self.areaCodigo.setObjectName("areaCodigo")
        self.verticalLayout.addWidget(self.areaCodigo)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 27))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 27))
        self.frame_2.setStyleSheet("background-color: #013750")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rodar = QtWidgets.QPushButton(self.frame_2)
        self.rodar.setMinimumSize(QtCore.QSize(0, 27))
        self.rodar.setMaximumSize(QtCore.QSize(70, 16777215))
        self.rodar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rodar.setStyleSheet("#rodar{\n"
"\n"
"    background-color: #00FF00;\n"
"    color:#02031a;\n"
"    border: solid 0 0 1 0;\n"
"\n"
"}\n"
"\n"
"#rodar:hover{\n"
"    color:white;\n"
"}\n"
"")
        self.rodar.setObjectName("rodar")
        self.verticalLayout_2.addWidget(self.rodar)
        self.verticalLayout.addWidget(self.frame_2)
        SimpleEditor.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(SimpleEditor)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 740, 28))
        self.menuBar.setMinimumSize(QtCore.QSize(0, 28))
        self.menuBar.setObjectName("menuBar")
        self.menuArquivo = QtWidgets.QMenu(self.menuBar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuSalvar = QtWidgets.QMenu(self.menuArquivo)
        self.menuSalvar.setObjectName("menuSalvar")
        self.menuEditar = QtWidgets.QMenu(self.menuBar)
        self.menuEditar.setObjectName("menuEditar")
        SimpleEditor.setMenuBar(self.menuBar)
        self.actionAbrir = QtWidgets.QAction(SimpleEditor)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalvar_como = QtWidgets.QAction(SimpleEditor)
        self.actionSalvar_como.setObjectName("actionSalvar_como")
        self.actionhfmjkjh = QtWidgets.QAction(SimpleEditor)
        self.actionhfmjkjh.setObjectName("actionhfmjkjh")
        self.actionSalvar_como_2 = QtWidgets.QAction(SimpleEditor)
        self.actionSalvar_como_2.setObjectName("actionSalvar_como_2")
        self.actionPython = QtWidgets.QAction(SimpleEditor)
        self.actionPython.setObjectName("actionPython")
        self.actionC = QtWidgets.QAction(SimpleEditor)
        self.actionC.setObjectName("actionC")
        self.actionJava = QtWidgets.QAction(SimpleEditor)
        self.actionJava.setObjectName("actionJava")
        self.menuArquivo.addAction(self.menuSalvar.menuAction())
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addAction(self.actionSalvar_como)
        self.menuEditar.addAction(self.actionPython)
        self.menuEditar.addAction(self.actionC)
        self.menuEditar.addAction(self.actionJava)
        self.menuBar.addAction(self.menuArquivo.menuAction())
        self.menuBar.addAction(self.menuEditar.menuAction())

        self.retranslateUi(SimpleEditor)
        QtCore.QMetaObject.connectSlotsByName(SimpleEditor)

    def retranslateUi(self, SimpleEditor):
        _translate = QtCore.QCoreApplication.translate
        SimpleEditor.setWindowTitle(_translate("SimpleEditor", "MainWindow"))
        self.rodar.setText(_translate("SimpleEditor", "Executar"))
        self.menuArquivo.setTitle(_translate("SimpleEditor", "Arquivo"))
        self.menuSalvar.setTitle(_translate("SimpleEditor", "Novo"))
        self.menuEditar.setTitle(_translate("SimpleEditor", "Linguagem"))
        self.actionAbrir.setText(_translate("SimpleEditor", "Abrir"))
        self.actionSalvar_como.setText(_translate("SimpleEditor", "Salvar"))
        self.actionhfmjkjh.setText(_translate("SimpleEditor", "hfmjkjh"))
        self.actionSalvar_como_2.setText(_translate("SimpleEditor", "Salvar como"))
        self.actionPython.setText(_translate("SimpleEditor", "Python"))
        self.actionC.setText(_translate("SimpleEditor", "C"))
        self.actionJava.setText(_translate("SimpleEditor", "Java"))
